# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: JDK 11

on:
  push:
    branches: [ 3.x ]
  pull_request:
    branches: [ 3.x ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up JDK 11
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Cache Gradle packages
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-1-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-1-
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Verify generated module-info
      run: ./gradlew -PjavaCompatibility=9 jar
    - name: Build RxJava
      run: ./gradlew build --stacktrace
    - name: Generate Javadoc
      run: ./gradlew javadoc --stacktrace
