# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Snapshot

on:
  push:
    branches: [ '3.x' ]
    
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.repository == 'ReactiveX/RxJava'
    permissions:
      contents: write
    env:
      # ------------------------------------------------------------------------------ 
      CI_BUILD_NUMBER: ${{ github.run_number }}
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up JDK 8
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Cache Gradle packages
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-${{ secrets.CACHE_VERSION }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Grant execute permission for push
      run: chmod +x push_javadoc.sh
    - name: Build RxJava
      run: ./gradlew build --stacktrace --no-daemon
    - name: Upload Snapshot
      run: ./gradlew -PreleaseMode=branch publish --no-daemon --no-parallel --stacktrace
      env:
        # Define secrets at https://github.com/ReactiveX/RxJava/settings/secrets/actions
        # ------------------------------------------------------------------------------ 
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USER }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
    - name: Upload to Codecov  
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
    - name: Push Javadoc
      run: ./push_javadoc.sh
        # Define secrets at https://github.com/ReactiveX/RxJava/settings/secrets/actions
        # ------------------------------------------------------------------------------
      env:
        JAVADOCS_TOKEN: ${{ secrets.JAVADOCS_TOKEN }}
